from dataclasses import dataclass
from typing import Protocol


@dataclass(frozen=True, slots=True)
class StoredFile:
    identifier: str
    mime_type: str
    extension: str
    size: int


class DocumentStorage(Protocol):
    async def save_input(self, job_id: str, data: bytes, mime_type: str) -> StoredFile: ...
    async def read_input(self, identifier: str) -> bytes: ...
    async def save_result(
        self, job_id: str, data: bytes, mime_type: str, extension: str
    ) -> StoredFile: ...
    async def read_result(self, identifier: str) -> bytes: ...
    async def delete_file(self, identifier: str) -> None: ...
    async def delete_job_files(self, job_id: str) -> None: ...
    async def cleanup_expired(self, active_identifiers: set[str] | None = None) -> int: ...
    async def healthcheck(self) -> bool: ...
